<a href="https://colab.research.google.com/github/jiyeonjin/0624_new/blob/main/0702_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [427]:
import numpy
arr=numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [428]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [429]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [430]:
import numpy as np
arr=np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [431]:
import numpy as np
arr=np.array(42)
print(arr)

42


In [432]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [433]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [434]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [435]:
import numpy as np
a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [436]:
import numpy as np
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print('number of dimensions :',arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [437]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[0])

1


In [438]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[1])

2


In [439]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[2]+arr[3])

7


In [440]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st row: ',arr[0,1])

2nd element on 1st row:  2


In [441]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('5th element on 2nd row: ',arr[1,4])

5th element on 2nd row:  10


In [442]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


In [443]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('Last element from 2nd dim: ',arr[1,-1])

Last element from 2nd dim:  10


In [444]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [445]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[4:])

[5 6 7]


In [446]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[:4])

[1 2 3 4]


In [447]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


In [448]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [449]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


In [450]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [451]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,2])

[3 8]


In [452]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [453]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr.dtype)

int64


In [454]:
import numpy as np
arr=np.array(['apple','banana','cherry'])
print(arr.dtype)

<U6


In [455]:
import numpy as np
arr=np.array([1,2,3,4],dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [456]:
import numpy as np
arr=np.array([1,2,3,4],dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [457]:
import numpy as np
arr=np.array([1.1,2.1,3.1])
newarr=arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [458]:
import numpy as np
arr=np.array([1.1,2.1,3.1])
newarr=arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [459]:
import numpy as np
arr=np.array([1,0,3])
newarr=arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [460]:
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [461]:
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[0]=42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [462]:
import numpy as np

arr=np.array([1,2,3,4,5])
x=arr.view()
x[0]=31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [463]:
import numpy as np

arr=np.array([1,2,3,4,5])

x=arr.copy()
y=arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [464]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [465]:
import numpy as np

arr=np.array([1,2,3,4],ndmin=5)

print(arr)
print('shape of array :',arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


# Numpy 배열 재구성

reshape(x, y) -> 배열 모양 변경 (요소 수 같아야 함)

reshape(-1, y) ->	자동 크기 계산

뷰(view) -> 반환	데이터 복사 안 함 (원본 영향 가능)



In [466]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [467]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [468]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
print(arr.reshape(2,4).base)

[1 2 3 4 5 6 7 8]


In [469]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
newarr=arr.reshape(2,2,-1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [470]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr=arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


# Numpy 배열 반복


In [471]:
import numpy as np

arr=np.array([1,2,3])

for x in arr:
  print(x)

1
2
3


In [472]:
import numpy as np

arr=np.array([[1,2,3],[4,5,6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [473]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [474]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [475]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)


1
2
3
4
5
6
7
8
9
10
11
12


In [476]:
import numpy as np

arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [477]:
import numpy as np
arr=np.array([1,2,3])

for x in np.nditer(arr, flags=['buffered'],op_dtypes=['S']):
  print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [478]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [479]:
import numpy as np

arr=np.array([1,2,3])

for idx, x in np.ndenumerate(arr):
  print(idx,x)

(0,) 1
(1,) 2
(2,) 3


In [480]:
import numpy as np

arr=np.array([[1,2,3,4],[5,6,7,8]])

for idx, x in np.ndenumerate(arr):
  print(idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


# Numpy 배열 결합

In [481]:
import numpy as np

arr1=np.array([1,2,3])

arr2=np.array([4,5,6])

arr=np.concatenate((arr1,arr2))

print(arr)

[1 2 3 4 5 6]


In [482]:
import numpy as np

arr1=np.array([[1,2],[3,4]])

arr2=np.array([[5,6],[7,8]])

arr=np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [483]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [484]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [485]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [486]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


# Numpy 배열 분할

In [487]:
import numpy as np

arr=np.array([1,2,3,4,5,6])

newarr=np.array_split(arr,3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [488]:
import numpy as np

arr=np.array([1,2,3,4,5,6])

newarr=np.array_split(arr,4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [489]:
import numpy as np

arr=np.array([1,2,3,4,5,6])

newarr=np.array_split(arr,3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [490]:
import numpy as np

arr=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])

newarr=np.array_split(arr,3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [491]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [492]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)


[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [493]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# Numpy 배열 검색

In [494]:
import numpy as np

arr=np.array([1,2,3,4,5,4,4])

x=np.where(arr==4)

print(x)

(array([3, 5, 6]),)


In [495]:
import numpy as np

arr=np.array([1,2,3,4,5,6,7,8])

x=np.where(arr%2==0)

print(x)

(array([1, 3, 5, 7]),)


In [496]:
import numpy as np

arr=np.array([1,2,3,4,5,6,7,8])

x=np.where(arr%2==1)

print(x)

(array([0, 2, 4, 6]),)


In [497]:
import numpy as np

arr=np.array([6,7,8,9])

x=np.searchsorted(arr,7)

print(x)

1


In [498]:
import numpy as np

arr=np.array([6,7,8,9])

x=np.searchsorted(arr,7,side='right')

print(x)

2


In [499]:
import numpy as np

arr=np.array([1,3,5,7])

x=np.searchsorted(arr, [2,4,6])

print(x)

[1 2 3]


# Numpy 정렬 배열

In [500]:
import numpy as np

arr=np.array([3,2,0,1])

print(np.sort(arr))

[0 1 2 3]


In [501]:
import numpy as np

arr=np.array(['banana','cherry','apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [502]:
import numpy as np

arr=np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [503]:
import numpy as np

arr=np.array([[3,2,4],[5,0,1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


# Numpy 필터 배열

In [504]:
import numpy as np

arr=np.array([41,42,43,44])

x=[True, False, True, False]

newarr=arr[x]

print(newarr)

[41 43]


In [505]:
import numpy as np

arr=np.array([41,42,43,44])

filter_arr=[]

for element in arr:
  if element>42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr=arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [506]:
import numpy as np

arr=np.array([1,2,3,4,5,6,7])

filter_arr=[]

for element in arr:
  if element%2==0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr=arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


In [507]:
import numpy as np

arr=np.array([41,42,43,44])

filter_arr=arr>42

newarr=arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [508]:
import numpy as np

arr=np.array([1,2,3,4,5,6,7])

filter_arr=arr%2==0

newarr=arr[filter_arr]

print(filter_arr)
print((newarr))

[False  True False  True False  True False]
[2 4 6]
